### ISSUE TITLE
Crash when teleporting from overworld to nether.

### ISSUE THREAD

**Issue by BabblingFishes** [itsmeow/QuickTeleports#1]
I've been using QuickTeleports v1.14.4-1.1.1 on a forge-1.14.4-28.2.0 server. Every time I'm in the overworld and use /tpa \<username\> to warp to someone in the nether, the server crashes: [crash-2020-03-23_17.33.11-server.txt](https://github.com/itsmeow/QuickTeleports/files/4372544/crash-2020-03-23_17.33.11-server.txt)

When I start the server back up and hop back on, I am in the nether, but at the same coordinates that I originally was at in the overworld (which usually leads to death).

**Comment by itsmeow** [comment]
erm... there's an access transformer that's supposed to apply here so something about your forge install is messed up
