### ISSUE TITLE
Timeout not working

### ISSUE THREAD

**Issue by EnderMelody** [itsmeow/QuickTeleports#2]
teleporting is allowed immediately even with with it set to 900 seconds
Version: 1.12.2
QuickTeleports v1.12.2-1.1.1

**Comment by itsmeow** [comment]
QuickTeleports has no "timeout" feature. I have no idea what you're talking about.

**Comment by EnderMelody** [comment]
https://imgur.com/a/SjAHbKS

**Comment by itsmeow** [comment]
That is for requests. That is when you send a request, how long it takes to get cancelled. There is no "countdown" feature.

**Comment by EnderMelody** [comment]
oh my bad. thats a shame, but thanks for the nice mod anyways
